name: pre-commit-uv
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  uv-install:
    description: whether to install uv (true=always, false=never, auto=only if not already available)
    required: false
    default: 'auto'
runs:
  using: composite
  steps:
  - name: Check if uv is already installed
    if: inputs.uv-install == 'auto'
    id: check-uv
    run: command -v uv && echo "installed=true" >> "$GITHUB_OUTPUT" || echo "installed=false" >> "$GITHUB_OUTPUT"
    shell: bash
  - name: Install the latest version of uv
    if: inputs.uv-install == 'true' || (inputs.uv-install == 'auto' && steps.check-uv.outputs.installed != 'true')
    uses: astral-sh/setup-uv@v7
    with:
      enable-cache: true
      cache-dependency-glob: '.pre-commit-config.yaml'
  - run: uv run --isolated --no-sync true && echo "pythonLocation=$(uv python find)" >>$GITHUB_ENV
    shell: bash
  - uses: actions/cache@v5
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: |
      if [ -f pyproject.toml ]; then
        uv run --no-sync --with pre-commit-uv pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      else
        uvx --with pre-commit-uv pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      fi
    shell: bash
