name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  uv_version:
    description: use a specific version of uv (default latest)
    required: false
    default: latest
runs:
  using: composite
  steps:
  - name: Install the latest version of uv
    uses: astral-sh/setup-uv@v6
    with:
      enable-cache: true
      cache-dependency-glob: '.pre-commit-config.yaml'
      uv-version: ${{ inputs.uv_version }}
  - run: uv run --isolated --no-sync true && echo "pythonLocation=$(uv python find)" >>$GITHUB_ENV
    shell: bash
  - uses: actions/cache@v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: uvx --python '${{ env.pythonLocation }}' --with pre-commit-uv pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
